export const allowedCountries = [
  "DE",
  "FR",
  "IT",
  "ES",
  "PL",
  "UA",
  "RO",
  "NL",
  "BE",
  "CZ",
  "GR",
  "SE",
  "PT",
  "HU",
  "CH",
  "AT",
  "BG",
  "DK",
  "FI",
  "NO",
  "US",
  "GB",
  "IE",
  "IS"
];

export const supportedLangs = new Set([
  "al",
  "bg",
  "cz",
  "da",
  "de",
  "el",
  "en",
  "fi",
  "fr",
  "hr",
  "hu",
  "it",
  "la",
  "lt",
  "mk",
  "no",
  "nl",
  "pl",
  "pt",
  "ro",
  "ru",
  "sv",
  "sk",
  "sl",
  "sp",
  "es",
  "sr",
  "tr",
  "ua",
  "uk",
  "vi",
]);

export const dayTranslations: Record<string, { today: string; tomorrow: string }> = {
  cs: { today: "Dnes", tomorrow: "Zítra" },
  sk: { today: "Dnes", tomorrow: "Zajtra" },
  uk: { today: "Сьогодні", tomorrow: "Завтра" },
  ru: { today: "Сегодня", tomorrow: "Завтра" },
  pl: { today: "Dziś", tomorrow: "Jutro" },
  de: { today: "Heute", tomorrow: "Morgen" },
  fr: { today: "Aujourd’hui", tomorrow: "Demain" },
  es: { today: "Hoy", tomorrow: "Mañana" },
  en: { today: "Today", tomorrow: "Tomorrow" },
};
